### ISSUE TITLE
Check URLs starting with http or https when adding ShortURLs

### ISSUE THREAD

**Issue by fs366e2spm** [FBoucher/AzUrlShortener#100]
Hi,

Discovered a strange behavior when I added some links. Missed that they didn't start with http or https but effect was, they weren't working, no redirect.

Either it should be checked during link creation that the Link starts with http(s) or the redirect should add it, if it's not available.

- [x] add validation at creation time in the UI
- [x] add validation at creation time in the UI

**Comment by FBoucher** [comment]
You are totally right @fs366e2spm this is a bug!
Thank you for your help. 
TASKS:
[ ] add validation at creation time in the UI
[ ] add validation in the AzFunction and return a smart error message

**Comment by FBoucher** [comment]
@all-contributors add @fs366e2spm for bug, idea
