### ISSUE TITLE
Deploy template from private repo

### ISSUE THREAD

**Issue by HighWatersDev** [FBoucher/AzUrlShortener#104]
I would highly appreciate any guidance on how to deploy this project from private repo. We use Github Enterprise and I just can't figure out the way to link the deployment to my private repo.

Thanks!

**Comment by FBoucher** [comment]
That's an excellent question @HighWatersDev, I think a GitHub Action could probablty do the things. I will add this in the TODOs. 
Godd Idea!

**Comment by fs366e2spm** [comment]
Hi @HighWatersDev, @FBoucher 
I tried to use the Deploy button from my fork and used that as the Git Hub URL (e.g. https://github.com/fs366e2spm/AzUrlShortener.git).
![image](https://user-images.githubusercontent.com/52791126/84075900-2ad5bc00-a9d5-11ea-8618-b62765478a7c.png)

Not sure if this is a way which really works fine, at least the components were deployed, did not do lots of tests, though... and of course no code changes in my fork.
![image](https://user-images.githubusercontent.com/52791126/84076090-75efcf00-a9d5-11ea-917c-3fd6b40e2415.png)

@HighWatersDev  - If you want to test it further, I would be happy for feedback if this works fine.

**Comment by FBoucher** [comment]
I will close this issue @fs366e2spm, you can deploy the project from anywhere, but maybe not using the automatic method provided in the instructions. (this was intent to help as most people as possible and make it easy)

To deploy manually have the code locally and use zip-deploy or Visual Studio (IDE or Code)
