### ISSUE TITLE
Info: Reducing costs for Blazor Admin UI for current App Service plan setup

### ISSUE THREAD

**Issue by fs366e2spm** [FBoucher/AzUrlShortener#106]
Hi,
Currently, during the automated Azure resource deployment an App Service Plan in the Production workload (Plan B1) is created which costs approx. 50$ per month. One of the B1 pricing plan feature is the "always on".

As long as it's not used in a productive environment and doesn't need to be on 24x7 and as this is "only" for the Admin UI I changed the App Service Plan to the Dev/Test workload and used the F1 pricing tier which includes 60min computing power per DAY. Should be more than enough for the Admin UI to create new URLs. With that it costs also just a few cents per day until the new [TinyBlazorAdmin ](https://github.com/FBoucher/TinyBlazorAdmin) is ready 🥳
![AppServicePlan_F1_60min_free_per_day](https://user-images.githubusercontent.com/52791126/83802840-c2709d00-a6ab-11ea-9e46-efd3fb267f32.png)

Yeah, F1 doesn't allow custom domains to call the Blazor Admin UI directly - so I'm using an own ShortURL 😎 and there I configured a custom domain.

Maybe this could go into documentation or otherwise just as info and can be ignored.

**Comment by FBoucher** [comment]
Yes now that Blazor web assembly is GA and Staticweb App (SWA) is out... this is where https://github.com/FBoucher/TinyBlazorAdmin will shine :)

**Comment by FBoucher** [comment]
Quick update to mention the [TinyBlazorAdmin ](https://github.com/FBoucher/TinyBlazorAdmin )interface is mostly done. 🎉
The thing left is to make it easy to deploy and integrated it smoothly with this project.

**Comment by FBoucher** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/c9fd5973-c9eb-4a54-bfc8-9f8ff7955c3a-1d2dd36b-6b40-4c19-aa4b-00c0c130b480-v1.png?transparent=1&palette=1&width=246)
It's finally done! Version 2.0 it's super budget-friendly... mostly free!
