### ISSUE TITLE
Problem using UrlShortener from Postman

### ISSUE THREAD

**Issue by diego-sorribas** [FBoucher/AzUrlShortener#107]
Hello, I can use the sortener from the admin panel , my problem is using it from Postman this is my request:

```
POST /api/UrlShortener?code=XXXHTTP/1.1
Host: shortenertoolsredpagoskinzv.azurewebsites.net
Content-Type: application/json

{
    "url": "https://solcre-promo-redpagos-ui.azurewebsites.net/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2Nlc3NfdG9rZW4iOiIxZTIwMTcyYjM4YzU4N2M0M2I2YTg3MDcyZWMyMWQ0MThlMjZhNDVmIiwiZXhwaXJlc19pbiI6Mjg4MDAsInRva2VuX3R5cGUiOiJiZWFyZXIiLCJzY29wZSI6bnVsbCwicmVmcmVzaF90b2tlbiI6IjUyYWFkZTAxNDM1NzY3OTU0MzFjYjgxZmVjYmQ1ODNjZmVkMmEzZWEifQ.s62CjCI9yEMIjK3z-djoYc4zhuGlBWtLohpkaJmSu6M",
    "vanity": ""
}
```

And it return me this:

```
{
    "ClassName": "System.NullReferenceException",
    "Message": "Object reference not set to an instance of an object.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at Cloud5mins.Function.UrlShortener.Run(HttpRequestMessage req, ILogger log, ExecutionContext context) in D:\\home\\site\\repository\\src\\shortenerTools\\UrlShortener\\UrlShortener.cs:line 64",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2147467261,
    "Source": "shortenerTools",
    "WatsonBuckets": null
}

```
Any idea what could be? Im using the default (functtion key) url.

**Comment by ThDJRenton** [comment]
same issue here, frustrating....must be something obvious?

**Comment by fs366e2spm** [comment]
Hmm, does work here for me. But unfortunately I don't know what could be wrong on your side.

_POST https://myowndomain.xyz/api/UrlShortener?code=xxxxxx HTTP/1.1
content-type: application/json
{
  "title": "FBoucher AzUrlShortener How it works",
  "url": "https://github.com/FBoucher/AzUrlShortener/blob/master/how-it-works.md",
  "vanity": "fbbb"
}_


Response:
_HTTP/1.1 200 OK
Content-Length: 236
Content-Type: application/json; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Request-Context: appId=cid-v1:xxxxxx
Set-Cookie: ARRAffinity=123456;Path=/;HttpOnly;Domain=myowndomain.xyz
Date: Sat, 13 Jun 2020 12:31:56 GMT
Connection: close_
_{
  "ShortUrl": "https://myowndomain.xyz/fbbb",
  "LongUrl": "https://github.com/FBoucher/AzUrlShortener/blob/master/how-it-works.md",
  "Title": "FBoucher AzUrlShortener How it works"
}_

**Comment by ThDJRenton** [comment]
Ok, so if the code works for others, must be an account specific issue related to the storage account access I would expect...very strange!

**Comment by FBoucher** [comment]
Awesome thanks for this!
We should add more parameter/ error messages in the Functions... 
#130 and #131
