### ISSUE TITLE
Feature request (idea): Add Expiry Date

### ISSUE THREAD

**Issue by fs366e2spm** [FBoucher/AzUrlShortener#110]
Adding a date until the Short URL is valid. Afterwards it might get automatically archived or date is checked and can't be called anymore.

**Comment by FBoucher** [comment]
Definitely a good idea.
Thanks @fs366e2spm

**Comment by FBoucher** [comment]
It doesn't archive automatically but the end date is now supported with PR Implementing Schedules features #272
