### ISSUE TITLE
Feature request (idea): Configurable minimum length for shortened url part

### ISSUE THREAD

**Issue by ThDJRenton** [FBoucher/AzUrlShortener#113]
In order to make the end url less guessable, ability to increase minimum length of the shortened URL returned, currently starts at the lowest in table of 2 characters in length, but I might want to force it to be at least 5!

**Comment by FBoucher** [comment]
Interesting... 
Yes I guess we could do something like that.
@ThDJRenton feel free to suggest a fix for that.

**Comment by ThDJRenton** [comment]
> Interesting...
> Yes I guess we could do something like that.
> @ThDJRenton feel free to suggest a fix for that.

@FBoucher Could you point me to the shortening code method? I think i've found it but not sure! 😄

**Comment by Hedlund01** [comment]
@ThDJRenton you can find the vanity encoder in Utility.cs at line 25, the function is named Encode :D

**Comment by ThDJRenton** [comment]
Just an update on this, has anyone managed to make the vanity part random not a sequential code?

**Comment by ThDJRenton** [comment]
This was resolved in V2 release (by me) 👍

**Comment by FBoucher** [comment]
Yes it would be a nice config to add @ThDJRenton
