### ISSUE TITLE
Info: New Admin UI: SharePoint List

### ISSUE THREAD

**Issue by fs366e2spm** [FBoucher/AzUrlShortener#121]
Hi @FBoucher,

I created a SharePoint list and I'm using this as an alternative Admin UI:
![SharePointList_UrlShortener](https://user-images.githubusercontent.com/52791126/84700221-194f5f80-af53-11ea-8323-73dc78c6258e.png)

The SharePoint list uses some PowerAutomate Flows which create, update, archive, etc. the Urls via the Azure Function URL.
If you see that as valid Admin UI and would like to add it I can provide more information.
A SharePoint list has some large benefits as search, grouping, filtering, etc. is already there out-of-the-box.

The connectors used in these Flows require unfortunately a premium license. There are multiple ways to call the Azure Functions (Azure Function connector, HTTP connector, etc,) but everything requires premium license. The Flows are currently just basic and use an HTTP call. This should be done better and more secure by storing the Azure Function key or the URL in Key Vault and calling it via API management (all of them require premium license as well).

**Comment by FBoucher** [comment]
This is super cool @fs366e2spm!
If you have the step by step instruction somewhere let's add a reference. Or you can also create a new file in this repo!
Let us know if you need any help

**Comment by fs366e2spm** [comment]
Provided information for PowerAutomate_Flow_as_UI in https://github.com/FBoucher/AzUrlShortener/pull/129
The SharePoint List UI is WIP.

Not sure if I did all correct with check-in the changes in github. Github is pretty new for me - I'm still learning...

**Comment by fs366e2spm** [comment]
Hi @FBoucher 
I finished all to use a SharePoint list as admin UI (including Flows and documentation).
Into which branch (vnext?) should I merge it?
https://github.com/fs366e2spm/AzUrlShortener/tree/M365SharePointList_as_UI

Do you prefer to have this in the main project or should I add it as my GitHub project and you link to it?

**Comment by FBoucher** [comment]
Hi @fs366e2spm,
So that looks really nice. 
To have it merged into this repo you will need to first bring the changes from this repo since you fork it.
Then you can do a PR to vNext.

Let me know if you need guidance to update from upstream.

**Comment by fs366e2spm** [comment]
PR #153 created to vNext
https://github.com/FBoucher/AzUrlShortener/pull/153

Hope I did it correct.
