### ISSUE TITLE
On prem implementation?

### ISSUE THREAD

**Issue by murugaratham** [FBoucher/AzUrlShortener#124]
Is it possible to make storage class implementation via interface? so that there's an option to host this wonderful project on-premise

**Comment by FBoucher** [comment]
@murugaratham do you mean for dev/test purposes, or in production?

**Comment by murugaratham** [comment]
For production, there are organisation that don’t embrace cloud 😔

**Comment by FBoucher** [comment]
It's okay to prefer on-prem. However this solution is really build for the cloud. 
You could get inspired by the code. the Azure Function could be an API running on a local server with the web site.

**Comment by FBoucher** [comment]
I will now close this issue.
