### ISSUE TITLE
Clicking into urls page gives error 

### ISSUE THREAD

**Issue by krillehbg** [FBoucher/AzUrlShortener#132]
Hi,
inside admin when logged in i click urls then i get
An error has occurred. This application may no longer respond until reloaded. Reload

Clicking Reload button just gives me a blank page and from console i can read this

The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

It has been working on and off

Any clues?

**Comment by FBoucher** [comment]
I wasn't able to reproduce.
I'm sorry @krillehbg, I hope the problem was fixed. If you still have that try to find some steps to reproduce.
