### ISSUE TITLE
Deploy to Azure fails

### ISSUE THREAD

**Issue by ravin4m** [FBoucher/AzUrlShortener#133]
<img width="1247" alt="Screen Shot 2020-06-23 at 3 41 19 PM" src="https://user-images.githubusercontent.com/48219079/85451852-4bbb1700-b568-11ea-9756-e018f3597a02.png">

**Comment by krillehbg** [comment]
Same problem here!

**Comment by tejeirodelrio** [comment]
Hi,

I would say that this is due to the fact that Azure expects to read the deployment file from the "master" branch but we have "main" branch instead.

Thanks,
Manuel

**Comment by FBoucher** [comment]
I'll fix the images and a few path still in error, but the deployment by the button should be fine now thanks to @thefisk
