### ISSUE TITLE
Feature request (idea): Allow bulk shortener generation

### ISSUE THREAD

**Issue by diego-sorribas** [FBoucher/AzUrlShortener#135]
I dont know if this is possible right now but when I want to use the function with many links Im using cURL and makes my process slower, I think is a good option to generate bulks shortener links..

Thanks!

**Comment by FBoucher** [comment]
What would be a good interface to to this?
How do you visualize the form or the flow, @diego-sorribas ?

**Comment by rugland** [comment]
A bulk import from excel would be nice. 

But it is possible to do today using the Azure Storage Explorer and importing the data directly to the table. Used it to bulk create 190 URLs for a project.
