### ISSUE TITLE
probleme

### ISSUE THREAD

**Issue by HorizonGa11** [FBoucher/AzUrlShortener#145]
salut comment utiliser ton raccourcisseur d’URL si on a pas de carte bancaire pour créer un compte azure ?? 
besoin d'une réponse rapidement 
merci bonne journée

**Comment by FBoucher** [comment]
Si tu es un etudiant tu peux aller https://c5m.ca/azFreeStudents
If you are a student try at: https://c5m.ca/azFreeStudents
