### ISSUE TITLE
Archive URLs via API calls

### ISSUE THREAD

**Issue by HighWatersDev** [FBoucher/AzUrlShortener#146]
Hi,

Could you add some guidance under Postman on how to archive the URLs via API calls? What would be the content of the body of the request?

**Comment by fs366e2spm** [comment]
Hi @HighWatersDev 

https://shortenertoolsk.....azurewebsites.net/api/UrlArchive

Method: **DELETE**

This are the required parameters:
{
  "RowKey": "xxxvalue",
  "PartitionKey": "s",
  "Vanity": "VanityValue"
}

{
  "Content-Type": "application/json"
}

**Comment by FBoucher** [comment]
Yes of course!

**Comment by FBoucher** [comment]
The documentation was update in PR #150
