### ISSUE TITLE
Post to Tables 409 error

### ISSUE THREAD

**Issue by Teellcory** [FBoucher/AzUrlShortener#163]
When using UrlRedirect or UrlShortener, there are POST requests to "<name>/Tables"
This always fails with a 409 error, but the services still perform their duties.

Here's an example of a UrlShortener request:
POST /Tables = 409
GET /UrlsDetails = 200
POST /Tables = 409
POST /UrlsDetails = 204
POST /Tables = 409
POST /UrlsDetails = 204

The command it executes is a URL that goes to <name>.table.core.windows.net:443/Tables()

**Comment by FBoucher** [comment]
I'm not sure I follow @Teellcory. 
/Tables is not a methods

Could you provide more context and details please.

**Comment by Teellcory** [comment]
All I have is Azure showing that information is the call stack. Something in the code is calling /Tables. I call the shortener and it in turn calls /Tables. It still shortens urls, but it also piles up these unnecessary calls to something that doesn't exist.

**Comment by FBoucher** [comment]
okay so you are creating a new url and in the callstack  this is showing up. 
interesting...

Same thing with or without vanity?

**Comment by Teellcory** [comment]
I haven't tried it with vanity, but I've also seen these /Tables calls when retrieving the URL. So it isn't just one method that does this, but seemingly all of them.

**Comment by FBoucher** [comment]
I don't see that in V2. Closing this issue.
