### ISSUE TITLE
ID Generation Consistency Questions

### ISSUE THREAD

**Issue by justinoverton** [FBoucher/AzUrlShortener#177]
I am investigating if this will work for what I need. I haven't used Azure Table Storage or Functions before so this may be obvious, but it isn't clear to me.

**Potential ID Collison between Generated and Vanity URLS?**: The ID generation is based on an incrementing number, but the check for an existing ID value is only done for vanity URLs. The number of entries required for a semi long vanity URL is quite high because of the encode method. However a very short vanity URL like: /buy is only id 2040. The collision may not come up for some time for a lot of uses, but eventually it will. So if I had vanity URL /buy created already. Then created a new URL and the nextid increments to 2040, the id would encode into "buy" and since it doesn't check if that already exists it will use that ID.

**ID Race Condition**: For my use-case I'm trying to send a direct link to a specific page for a specific user. These links are likely to get created in batch and close in time. Is the entire call in a transaction? When entityid is incremented and returned, is there a window where there is a race condition that two requests will have the same ID?

**Always Upserting?**: If any of the race conditions are valid concerns... should the SaveShortUrlEntity be used for both Create New and Updating? If there were an ID collision, when creating new this would be the spot that ends up updating the record instead of throwing some sort of duplicate key exception.

**Comment by Hedlund01** [comment]
You are totally right about the id collision, the new entry will override the older entry.

**Comment by FBoucher** [comment]
It's in VNext and will be part of the next release
