### ISSUE TITLE
Next version brings breaking changes, what should we do?

### ISSUE THREAD

**Issue by FBoucher** [FBoucher/AzUrlShortener#194]
The next version of the URL shortener leverage Azure Active Directory (AAD) for authentication. This will be incompatible with the current version.

What should we do!

- Tag this version and continue on v2. (meaning v1 will still be available but not updated)
- Move this "flavor" into a different branch? 
- Just move on and cause push the breaking changes
- other?

![bitmoji](https://sdk.bitmoji.com/render/panel/2196307c-2ceb-46f8-8bf4-4c3e3f34f93e-1d2dd36b-6b40-4c19-aa4b-00c0c130b480-v1.png?transparent=1&palette=1&width=246)

**Comment by fs366e2spm** [comment]
+1 for "Tag this version and continue on v2. (meaning v1 will still be available but not updated)"

if not then at least: Move this "flavor" into a different branch? and keep that branch (mark it for non deletion) ;-)

**Comment by FBoucher** [comment]
V2.0 is out!
