### ISSUE TITLE
Keep v1 one click deployment possible

### ISSUE THREAD

**Issue by FBoucher** [FBoucher/AzUrlShortener#206]
WIth things that moved around in V1. Some path, branch, files may need to be updated (aka hard code v1 properties) to make sure the one click deployment is still possible.

**Comment by fs366e2spm** [comment]
Hi @FBoucher, will you include the PRs for the additional UIs for v1 as well? Not sure if they will work with v2 so it might be good to have them in v1.
From which branch did you create v1? Seems not form vnext.
Thanks

**Comment by FBoucher** [comment]
Yes.
It's kind of why I did the different branch. You are totally right @fs366e2spm 
We need to "re-shape" the main ReadMe to make those UI more visible and target the proper version.

**Comment by FBoucher** [comment]
@fs366e2spm would you like to maintain [main-v1](https://github.com/FBoucher/AzUrlShortener/tree/main-v1)? Yo could bring the features you mentioned.

**Comment by fs366e2spm** [comment]
Hi @FBoucher 
I moved the documentation and the source files for the additional V1 Admin UIs to an own repository:
https://github.com/fs366e2spm/AzUrlShortener-v1-AdminUIs

Thought it might be easier so you could clean-up the admin UI readme page for the V2 and link to the additional v1 Admin Uis if you want.
