### ISSUE TITLE
Custom Domain name is not return

### ISSUE THREAD

**Issue by FBoucher** [FBoucher/AzUrlShortener#218]
It's add a Configuration in the Azure Function. If present and filled it will be used. Otherwise the current Request.Host value will be.

**Comment by chuckgiddens** [comment]
Can you tell me the configuration property name?  Or documentation on how to setup a custom domain?

**Comment by FBoucher** [comment]
:)
I'm working on this... I push  into vNext the code still need to adjust the documentation. You will need to add a new Configuration setting named `customDomain` into the Azure Function Settings.
