### ISSUE TITLE
Change the default domain

### ISSUE THREAD

**Issue by mp93** [FBoucher/AzUrlShortener#236]
Hi @FBoucher ,

I was trying to change the default custom domain that is shortenertoolsgs7hf.azurewebsites.net. I would like to change it to something like abc.com. I would like to know if this can be done. If so how can this be implemented.
Can someone please help me with this issue.

**Comment by FBoucher** [comment]
Yes it can be done @mp93. Please refer to the documentation here: [Add a Custom Domain](https://github.com/FBoucher/AzUrlShortener/blob/main-v1/post-deployment-configuration.md#post-deployment-configuration-1), I also add this question in the [Q&A](https://github.com/FBoucher/AzUrlShortener/discussions/237)
