### ISSUE TITLE
Store the page title, along with the URL

### ISSUE THREAD

**Issue by surlydev** [FBoucher/AzUrlShortener#24]
When entering a URL to shorten, we should also store the page title.

For instance: the URL www.surlydev.net/me-in-a-mankini could display the page title "SurlyDev show's his curves in a fetching lime green mankini"

**Comment by FBoucher** [comment]
Great idea. Promoting this issue as a feature.

**Comment by FBoucher** [comment]
Let's add a property `Title`
It should also be visible when return by the Function `Urllist`

**Comment by FBoucher** [comment]
In progress in the branch feature/add-title
feel free to help :D
