### ISSUE TITLE
Delete all links or wipe link database.

### ISSUE THREAD

**Issue by DanyRamdas** [FBoucher/AzUrlShortener#276]
Hi is there a way to delete all links made?

I need to bulk refresh my links there for I want to delete all current links.

Thanks,

Dany

**Comment by FBoucher** [comment]
There is no bulk action right now from the user interface.
The fastest way (without installing anything) would be to use the Azure Portal.

![image](https://user-images.githubusercontent.com/2404846/112570583-ac5bd680-8dbc-11eb-8f83-3f40f1bbfb08.png)

From the Azure Portal, open the storage account. Using the Storage Explorer, open the tables and delete all the rows. You can select multiple rows by holding Shift.
