### ISSUE TITLE
[Improvement] Make vanities case insensitive

### ISSUE THREAD

**Issue by jpawlowski** [FBoucher/AzUrlShortener#293]
I noticed that currently redirects require vanities to be exactly as added to the database.
It would be nice to have these handled as case insensitive instead so that marketing guys could write codes however they want (and users could ignore upper cases and simply enter lower case only words that would still work the same way).

┆Issue is synchronized with this [Trello card](https://trello.com/c/fyCGerdF) by [Unito](https://www.unito.io)

**Comment by ThDJRenton** [comment]
I would just add that if we make them case insensitive it reduces the security, mildly. 👍

**Comment by Rcatalfu** [comment]
I think a good way to do this would be if we were to offer a checkbox to allow all variations, which behind the scenes creates the Short URLs for all variations.

**Comment by fboucher** [comment]
Related: https://github.com/fboucher/AzUrlShortener/issues/14
