### ISSUE TITLE
Poor Privacy - All urls can be iterated

### ISSUE THREAD

**Issue by firepacket** [FBoucher/AzUrlShortener#294]
`"ShortUrl": "http://c5m.ca/20"`

Everyone will be able to see your other users url. No privacy in this shortner.

**Comment by ThDJRenton** [comment]
I be amazed if you can guess the iterations in the version 2. The url's are random and non sequential, I added that feature 😄

**Comment by firepacket** [comment]
You still have to check the database to see if the url exists already. Take a look at this function that can run on the autoincrement sql id column and supports huge numbers all the way up to ulong with the shortest url possible, fastest time possible, no db lookups, and bigger privacy search space, and customizable prioritization.

https://gist.github.com/firepacket/8e9077792ea63a069ca6b0acf3dd4d21
