### ISSUE TITLE
v2 401 Error Help

### ISSUE THREAD

**Issue by 2xOu7** [FBoucher/AzUrlShortener#295]
Hi,

I am trying to onboard to the new v2 API. I only need the backend, which I have already deployed. I have also set up a new Identity Provider for the Functions by creating an AAD app according to the instructions.

I am able to successfully acquire a bearer token for the AAD app using the ADAL library, but when I pass in the token in the authorization header to call the UrlShorten API, the response I get is a 401 with message = "You do not have permission to view this directory or page."

Not sure why this is happening. Please let me know if you need any more information for debugging.

**Comment by FBoucher** [comment]
@2xOu7,  version 3 will simplify the Identity. Note however that all management functionalities are now part of the [TinyBlazorAdmin](https://github.com/FBoucher/TinyBlazorAdmin) project.
