### ISSUE TITLE
Usage metrics

### ISSUE THREAD

**Issue by surlydev** [FBoucher/AzUrlShortener#3]
The number of times a URL redirect is visited, should be stored (if required), so that popular links can be recognised.

**Comment by FBoucher** [comment]
Yes, excellent suggestion. That should be the primary feature we should add.

**Comment by FBoucher** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/5b7bff30-d7cc-4141-9f91-d77fa135057f-5b39d760-6a0b-41df-bf28-c9c1b9dae34c-v1.png?transparent=1&palette=1&width=246)
