### ISSUE TITLE
401 Unauthorised using Postman

### ISSUE THREAD

**Issue by NickRees91** [FBoucher/AzUrlShortener#359]
I have deployed the project in Headless mode, and followed all steps to the letter.
However, when trying to access the API using Postman, I get a 401 error.

The Function App doesn't have any authentication configured, and therefore should allow anonymous access? But this is not the case, it seems to want a token of some sort.

Have you got any advice on this issue.
Thank you for the brilliant project by the way, I'm a big fan!

**Comment by cklenk** [comment]
I do have this issue. I go to get function URL and just returns:

https://shortenertoolsxxxxx.azurewebsites.net/api/UrlShortener

**Comment by FBoucher** [comment]
For security and simplicity, this project only contains redirect functionalities. We moved the management to the [TinyBlazorAdmin](https://github.com/FBoucher/TinyBlazorAdmin). Today the Function App is part of that project as the backend API.
