### ISSUE TITLE
Not authorized

### ISSUE THREAD

**Issue by amabdallah** [FBoucher/AzUrlShortener#367]
I deployed the app and logged in to my account but when I click at Manage URLs, it tells me: Not authorized
https://admshortenertoolsrjvau.azurewebsites.net/urls

![image](https://user-images.githubusercontent.com/3268971/160846649-ed67a17f-f67c-4998-9454-9b6cf490757b.png)

**Comment by FBoucher** [comment]
Hi @amabdallah you can now deploy https://github.com/FBoucher/TinyBlazorAdmin alone.
If you don't have any URLs delete the previous deployment and re-deploy AzureUrlShortener with the new version (v3)
It should be fixed
