### ISSUE TITLE
Updates to Deploy Documentation

### ISSUE THREAD

**Issue by fatpacket** [FBoucher/AzUrlShortener#433]
Would it be possible to provide updated install docs?  The step by step doc seems to focus on Tiny Blazor Admin and not the shortner app.  Its mildly confusing. 
This project is great and love the notes about the re-write. Looking forwarding to being able to successfully run this

┆Issue is synchronized with this [Trello card](https://trello.com/c/PZDYa8f5) by [Unito](https://www.unito.io)

**Comment by FBoucher** [comment]
Yes, good idea. Thank you for the suggestion @fatpacket

**Comment by fatpacket** [comment]
I will happily test and validate documentation. Run through it and make edits as needed, but as of this moment I could not get it to work.

**Comment by FBoucher** [comment]
@fatpacket the documentation for the AzUrlShortener has been updated here: https://github.com/FBoucher/AzUrlShortener/wiki/Deployment-with-the-Deploy-to-Azure-button

**Comment by fatpacket** [comment]
Thank you! I got the URL Shortner installed and the test api redirect worked.  When I inserted a record to the table I am unable to access the short link via the functions url + / {{RowKey}}  I get a 404 not found.  So I tried to install BlazorTinyAdminv3 and followed those instruction but get an error that the SWA needs content deployed to it.  [See Issue Here](https://github.com/FBoucher/TinyBlazorAdmin/issues/94)

This function/api is exactly what I am looking along with the nice smooth front end. I am really hope you might be able to help me get this working.  Definitely want to discuss how to secure the api as well so that only my website can submit requests for shortening.  
Thank you for all the work to you and the team

**Comment by FBoucher** [comment]
@fatpacket until you have configured a custom domain and applied some rules you will need to use the `.../api/redirect/{vanity}` URL.

I created a new URL with Azure Storage following these [instructions](https://github.com/FBoucher/AzUrlShortener/wiki/How-to-Use-Azure-Storage-Explorer-as-Admin-Tools-for-AzUrlShortener#create-a-new-short-url), and it works. Have a look maybe you forgot something.

We will review the documentation about how to set up a custom domain, and deploy the TinyBlazorAdmin. 
Stay tuned for more.

**Comment by fatpacket** [comment]
Presuming the custom domain needs to be hosted with Azure.  Whats the linkage from the function to the custom domain? Where is all that setup? Or is it just the config variable?

**Comment by FBoucher** [comment]
@fatpacket all the doc is now up to date in the wiki.

![image](https://user-images.githubusercontent.com/2404846/205348663-31c7352a-4176-4c83-8cff-8c53d373e168.png)

Domain can come from elsewhere if you want my c5m.ca was bought on goDaddy...

**Comment by FBoucher** [comment]
@fatpacket is anything still missing?

**Comment by fatpacket** [comment]
I have run through the documentation and the custom domain video and documentation is working well.
The deployment works great from the button and creates all the required resources.
The Storage explorer is a decent front end but the documentation should include a how to for the TinyAdminv3 front end as well. When you review the TinyAdminv3 documentation you see my issue over there.   [TinyAdminv3 #94](https://github.com/FBoucher/TinyBlazorAdmin/issues/94)
