### ISSUE TITLE
multiple

### ISSUE THREAD

**Issue by trotroyanas** [FBoucher/AzUrlShortener#61]
Bonjour,
super idée, mais je voulais poser quelques questions pour voir si cela peut coller aux besoins de mon entreprise.
J'ai des envois de campagnes SMS mettons 5.000 sms, et nous devons avoir une url par sms sinon nous ne savons pas quel SMS a été cliqué, car en fonction d'un clic ou pas il y'a un scénario qui peut déclancher un autre SMS.
du coup je voulais savoir si c'est jouable sur de tres grand nombre on peut avoir 150.000 à 300.000 sms avec url unique par sms dans la meme campagne donc la rapidité de mise à jour par sms de l'url et la gestion des grands volumes d'url.
autre question est-ce que le projet peux gerer un domaine d'un client en gros http://toto.com/2wderf
et une autre client pour qui on utiliserais sont domaine http://tata.fr/5af5cdw0

Merci.
cH.

**Comment by FBoucher** [comment]
Bonjour @trotroyanas,
Je n'ai pas testé, mais les Azure Function et table storage sont fait pour ça.
Cependant aujourd'hui le projet n'a pas d'interface (frontend) qui permet de faire du "bulk" donc à moins de vous faire des scripts et d'appeler les API directement, vous allez devoir le faire un par un.

Et pour les grands nombres il est toujours possible changer de braquet tarifaire (scale-up). ET le projet actuel ne supporte pas de plusieurs noms de domaine en même temps,

**Comment by trotroyanas** [comment]
Bonjour 
merci de vos réponse pour le volume je pense en effet que c'est jouable.
par contre je suppose qu'il doit falloir changer quelque chose coté dns ?
pour pallier à plusieurs domaine peut'on déployer plusieurs fois la solution ?
après qu'il n'y ai pas d'interface aujourd'hui c'est pas bien grave.

:) cH.

**Comment by FBoucher** [comment]
Oui la solution peu etre deployer plusieurs fois dans la meme subscription. Il faut seulement donner un nom different. Je le fait constament ou j'ai la version que j'utilise et une version "demo" que j'utilise dans mes stream.
