### ISSUE TITLE
First time use

### ISSUE THREAD

**Issue by jvondermans** [FBoucher/AzUrlShortener#62]
Hi Frank,

First of all, a great idea of a shortner that you can manage yourself. I have deployed it to my own Azure subscription, but I can't get it to work. I must say, I'm not a developer so a lot of your info and comments are hard to understand (but with the help of google I seem to get further).
I've managed to install everything and log in to the web app, but then I'm stuck. There is no 'Add' button when you don't have a URL at all.
I've tried it with Postman (way out of my league), but I can't get the info because a link runs dead (https://github.com/FBoucher/AzUrlShortener/blob/master/src/adminTools/postman/README.md) the link for 'get the URL's'.

So if you have any info to get me a bit further that would be great!

Regards,
Jordy

**Comment by FBoucher** [comment]
I will review the deployment instruction. Can you help me by identifying where it became not clear (or less clear)?

**Comment by jvondermans** [comment]
Hi Frank,

I'm glad I can help. Hopefully this info can help you to improve the documentation.

The post-deployment info:
- info about a custom domain from Microsft is clear
- the FunctionApp screen is in the App Service Plan and not in the App Service (although the icons seem to indicate this). took me a while to find this ;-)
But when I found it, my screen doesn't represent the same as yours (I don't see any functions):
![image](https://user-images.githubusercontent.com/32496711/82290012-36b9f980-99a6-11ea-9648-e5dee25d60ef.png)

On the Postman page:
-I can go to the Postman page because the link is there. but having no coding experience or not being a developer, what should I do and where should I go?
-The link for getting the URL's is dead, I get a 404
-Create Short URL, I think the Postman usage needs more explaining. What URL do I need, do I need to add Extra bits (/api/ ?) in the URL, how to add the code (in the end I found it in Visual Studio Code).

Admin Blazor Frontend
The screenshot doesn't represend what I have in My screenshot. I also have some info that is already present an some is not there at all, should I alter it or has it been changed recently?

![image](https://user-images.githubusercontent.com/32496711/82291305-09227f80-99a9-11ea-85d5-10ddfa035d82.png)

hopefully this is info you can use to improve the documentation. Iif you need more help in reviewing, let me know!

Jordy

**Comment by FBoucher** [comment]
I think your deployment failed.
You don't have any functions in the Functions tree node.
I suggest you delete the resource group and start over.
