### ISSUE TITLE
azure based login

### ISSUE THREAD

**Issue by jvondermans** [FBoucher/AzUrlShortener#65]
it would be great if you could assign an Azure group that is able to use the service via the website with login. When using the app it easy to manage who can and who can't access the application.

Also the admin should be an Azure user, this way login is secured and not in plain text as it is now (also with MFA is enabled).

Regards,
Jordy

**Comment by FBoucher** [comment]
Yes, it could be really cool.
The current version is using Asp.Net Core Identity, but we could use AAD. 

In fact, that's exactly what will use a new frontend. We should start working on the frontend the week after Build.

**Comment by jvondermans** [comment]
Hi Frank,

That's good to hear! for now the frontend login with AAD is good enough, this way you don't have to explain to users how to login or create a new account.

Regards,
Jordy

**Comment by FBoucher** [comment]
I will close this issue. Version to works with Azure Active Directory (AAD)
![bitmoji](https://sdk.bitmoji.com/render/panel/3d81f2e3-dec8-4395-a284-9c21f770a7e6-1d2dd36b-6b40-4c19-aa4b-00c0c130b480-v1.png?transparent=1&palette=1&width=246)
