### ISSUE TITLE
Invalid login attempt

### ISSUE THREAD

**Issue by seb-sudo** [FBoucher/AzUrlShortener#66]
Followed the guide and deployed into my test subscription.

Getting Invalid login attempt when logging in.
I have double checked the email and pw on settings>configuration and all looks good

**Comment by FBoucher** [comment]
Is it a very strong password?

Identity requires that passwords contain:
- an uppercase character
- lowercase character
- a digit
- non-alphanumeric character
- must be at least six characters long.

**Comment by FBoucher** [comment]
Let's add this information into the documentation AND the meta-data of contains in the ARM template

**Comment by seb-sudo** [comment]
Ah, I was missing a non-alphanumeric - Sorted, thank you
