### ISSUE TITLE
Custom domain set up for app service, but it isn't being used for the URL.

### ISSUE THREAD

**Issue by IronManion** [FBoucher/AzUrlShortener#67]
Hey - 

Great tool.  Got it running on Azure and set up my custom domain for the app service, but it still generates a <service>.azurewebsite.net link v. a custom URL link.  

Do I need to add the custom URL to the function or the app service?  

Thanks!

**Comment by FBoucher** [comment]
@IronManion , once you set a custom domain to your Azure Function you need to edit the value of **AzFunctionUrl** in the configuration of the WebApp to use it.

![2020-05-18_16-46-10](https://user-images.githubusercontent.com/2404846/82258268-873e4200-9927-11ea-9f0b-15d93a734313.png)

**Comment by FBoucher** [comment]
Let's add this information in the documentation. Probably in the [post-deployment-configuration.md](https://github.com/FBoucher/AzUrlShortener/blob/master/post-deployment-configuration.md) page

**Comment by IronManion** [comment]
Happy to help out and do the docs for this.  

After doing the above, the redirects work, but the /url (i.e. manage URLs) now gives this error: "An error has occurred. This application may no longer respond until reloaded."

**Comment by IronManion** [comment]
Apologies if this should be obvious, but I am a bit new to some of the Azure stuff.

**Comment by FBoucher** [comment]
It's all good, your questions are excellent.
your link does NOT end by a `/` now contain extra spaces before or after?

Try to use the "advanced edit" it will show the son file those things may be easier to see using that view.

**Comment by IronManion** [comment]
Nope - JSON looks clean.

Login doesn't work either.  

I don't have a SSL cert bound - could that be it?

**Comment by IronManion** [comment]
Domain mappings:
![image](https://user-images.githubusercontent.com/36028632/82271467-b0ad9c80-992c-11ea-92fb-ec5c8ccbe64d.png)

![image](https://user-images.githubusercontent.com/36028632/82271510-d33fb580-992c-11ea-8cd0-5c8e378dd7d8.png)

The custom domain is only on the function, not the app service.  Removing the "A" record doesn't fix the issue.  Feels like some config needs to be updated.

**Comment by FBoucher** [comment]
with a CName I think you need to set the www in the URL. Next week (after Build) I will try to add more documentation for the SSL/ domain.  I didn't prioritize it because I was looking to have something that works... but its time now :)

**Comment by IronManion** [comment]
NP - happy to help try stuff out.  Good luck!

**Comment by fs366e2spm** [comment]
Yeah - got it to work. The SSL Binding for the custom domain is required, otherwise the Blazor UI can't load the "Manage URLs"

**Comment by IronManion** [comment]
Thanks!  I'll try that out today.

**Comment by HighWatersDev** [comment]
So, if I choose 'none' for frontend, there is no way to use custom URLs? I don't see AzFunctionUrl variable under Functions.

**Comment by FBoucher** [comment]
@HighWatersDev `AzFunctionUrl` is a configuration in the client to point to the Azure function.

By "custom URLs", do you mean your own domain name? Check [this doc]9https://docs.microsoft.com/en-ca/azure/app-service/app-service-web-tutorial-custom-domain?WT.mc_id=azurlshortener-github-frbouche) to map a domain to your Azure Function.

**Comment by HighWatersDev** [comment]
@FBoucher Thanks for the reply! I wanted to use functions without frontend. But I ended up just provisioning frontend since it's easier. I also added custom domain as per instruction.
I am able to navigate to the page and visit Admin page. But if I try to click on "Manage Urls" or "Logout" I get the below. And if I reload, I get 500/400 errors 
![image](https://user-images.githubusercontent.com/37680855/83698810-5c631780-a5d0-11ea-88c8-484f3adb0755.png)
![image](https://user-images.githubusercontent.com/37680855/83698898-99c7a500-a5d0-11ea-9ea6-82c5eba16927.png)

**Comment by fs366e2spm** [comment]
As discovered in my earlier post the Admin UI can only be loaded with a custom domain when the SSL Binding is done: 
> Yeah - got it to work. The SSL Binding for the custom domain is required, otherwise the Blazor UI can't load the "Manage URLs"

Here the manual / steps how I configured a custom domain to call the ShortURLs:

0. Setup your domain / subdomain in DNS (prerequisite) and ensure it's a CNAME and not an A record!
![0_DNS_CNAME_config](https://user-images.githubusercontent.com/52791126/83806200-6c065d00-a6b1-11ea-815a-cf6875ea9bed.png)

1. Open the ShortnerTools App Service and go to the custom domain navigation entry
![1_ShortnerTools_AppService__Custom_domains](https://user-images.githubusercontent.com/52791126/83804737-e08bcc80-a6ae-11ea-803d-1e378bdf830e.png)

2. add the custom domain
![2_Add_Custom_Domain](https://user-images.githubusercontent.com/52791126/83809872-79264a80-a6b7-11ea-8c1a-8bec0d6f6c0c.png)

3. validate the custom domain and when "Hostname availability" and "Domain ownership" have been verified press the "Add custom domain" button
![3_Validate_domain](https://user-images.githubusercontent.com/52791126/83806520-edf68600-a6b1-11ea-87e8-5f210eabf2aa.png)

 
4. The custom domain has been added, we now first need to create a certificate before we can add the binding
![4_AddBinding](https://user-images.githubusercontent.com/52791126/83807076-c81db100-a6b2-11ea-8cc4-1facc50d6dd4.png)

5. Create a free App Service Managed Certificate as described here (does not support DNS A-records):
- https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-bindings#prerequisites
- https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate#create-a-free-certificate-preview

> From the left navigation of your app, select TLS/SSL settings > Private Key Certificates (.pfx) > Create App Service Managed Certificate.
> 
> ![Create free certificate in App Service](https://docs.microsoft.com/en-us/azure/app-service/media/configure-ssl-certificate/create-free-cert.png)
> 
> Any non-naked domain that's properly mapped to your app with a CNAME record is listed in the dialog. Select the custom domain to create a free certificate for and select Create. You can create only one certificate for each supported custom domain.
> 
> When the operation completes, you see the certificate in the Private Key Certificates list.
> ![Create free certificate finished](https://docs.microsoft.com/en-us/azure/app-service/media/configure-ssl-certificate/create-free-cert-finished.png)
> 
> Important
> To secure a custom domain with this certificate, you still need to create a certificate binding. Follow the steps in [Create binding](https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-bindings#create-binding).


6. Go back to the Custom domain navigation entry as visible in step 2 and press the "Add binding" link as seen in step 4

7. Select your custom domain, the created certificate thumbprint which has been created in step 5 and "SNI SSL" as the SSL Binding
![7_create_certificate_binding](https://user-images.githubusercontent.com/52791126/83808893-d5886a80-a6b5-11ea-9cf0-c3268b57d250.png)

8. and finish - your vanity URLs can now be called via your custom domain! ✔
now you just need to change the URL in the azFunctionUrl config (it's in the admin "App Service") so you can copy the URLs from the Blazor UI
![8_change_azFunctionUrl](https://user-images.githubusercontent.com/52791126/83810560-9c9dc500-a6b8-11ea-9c1c-da2d99f2a79f.png)

**Comment by HighWatersDev** [comment]
@fs366e2spm Thanks!
I followed those steps precisely but I'm still unable to load "Manage Urls" page.
![image](https://user-images.githubusercontent.com/37680855/83828040-bb4a8e80-a6ad-11ea-874f-408b5d3404fe.png)

![image](https://user-images.githubusercontent.com/37680855/83828113-e503b580-a6ad-11ea-88ca-b2a366ab16f7.png)

![image](https://user-images.githubusercontent.com/37680855/83828172-09f82880-a6ae-11ea-8dc7-a62842e56e23.png)

![image](https://user-images.githubusercontent.com/37680855/83828255-37dd6d00-a6ae-11ea-80f4-f41daeddb1ed.png)

![image](https://user-images.githubusercontent.com/37680855/83828422-a02c4e80-a6ae-11ea-8d18-2843d03b39a8.png)

**Comment by fs366e2spm** [comment]
Hi @HighWatersDev 
As far as I can see you added the custom domain to the adm (Blazor UI) App Service. This doesn't work. I don't know why, tried that first as well and gave up. It also depends on why or where you would like to have the custom domain. I decided for me to NOT configure the custom domain for the Admin UI, instead I configured as described in my steps the custom domain on the App service which is actually called - where it also makes more sense from my point of view and there the custom domain works fine and so I could prevent the Blazor loading issues.

**Comment by HighWatersDev** [comment]
@fs366e2spm Thanks for the clarification. I was able to add custom domain to the actual UrlShortener functions and could create short urls with custom domain. As you noticed correctly, I was trying to add custom domain to the Blazor UI to have a webpage with custom url. Ideally, I'd like to have custom url for web UI but also make it available for other users.

**Comment by HighWatersDev** [comment]
@fs366e2spm @FBoucher following this guide, I configured custom domain for shortenertool App Service, now I can access UI and see URLs. I can copy it as 'https://custom_domain/vanity'. But when I follow this [guide](https://github.com/FBoucher/AzUrlShortener/blob/master/how-it-works.md) and send post request:
{
    "url": "https://docs.microsoft.com/en-ca/azure/azure-functions/functions-create-your-first-function-visual-studio",
    "title": "MS Docs - Create first function",
    "vanity": "Func"
}
I get back the original URL:
{
    "ShortUrl": "https://shortenertool#####azurewebsites.net/Func",
    "LongUrl": "https://docs.microsoft.com/en-ca/azure/azure-functions/functions-create-your-first-function-visual-studio",
    "Title": "MS Docs - Create first function"
}
Any idea how to get custom domain in return to POST request?

**Comment by fs366e2spm** [comment]
HI @HighWatersDev,
Now you can change the azFunctionUrl to your own domain (and maybe restart the app). From then on when you create new short URLs they are created with your own domain.

Regarding a custom domain for the Blazor UI - I solved it this way, that I created an own vanityURL (e.g. AdminUI), so you have exactly what you wanted - a custom domain to call it via 'https://custom_domain/AdminUI'

**Comment by HighWatersDev** [comment]
Thanks, @fs366e2spm !

This works as expected using Blazor UI. The issue I'm trying to figure out now is how to get ShortUrl with a custom domain using API alone without UI.
When I send POST request directly, in response I get Url with original domain ***.azurewebsites.net and not the custom domain. As in my previous comment.

Thanks for all the clarifications!

**Comment by avp411** [comment]
I'm having the same issue as @HighWatersDev I am only using the API and added a custom domain. I do not have the azFunctionURL since I didn't add the admin UI. Any way to get the API to return my custom domain?

**Comment by HighWatersDev** [comment]
@avp411 I ended up doing something as simple as string.replace("custom-domain.com", "***.azurewebsites.net").
To be clear, custom domain works, it was just not returning in API call. So, doing a simple string replacement in the response did the trick for me.

**Comment by DamienCalvert** [comment]
Is AzFunctionUrl still the thing to set in V2?
This value didn't exist and when I have created it, the UI still generates the URLs with the azurewebsite address and not the custom address.
The custom address is working is I change it manually.

**Comment by FBoucher** [comment]
it's not required in version 2.
There is a bug sometimes where the custom domain is not returned... 

**if it works once it will always work**. 

But for some deployment, it still returns the *.azurewebsites.net

**Comment by FBoucher** [comment]
This is now part of the documentation I will close this issue.
A HUGE thank you to @fs366e2spm for his help. 
![bitmoji](https://sdk.bitmoji.com/render/panel/15f269e9-79ff-42f5-b6f8-df81e1cb3847-1d2dd36b-6b40-4c19-aa4b-00c0c130b480-v1.png?transparent=1&palette=1&width=246)

**Comment by DamienCalvert** [comment]
> it's not required in version 2.
> There is a bug sometimes where the custom domain is not returned...
> 
> **if it works once it will always work**.
> 
> But for some deployment, it still returns the *.azurewebsites.net

Hmmm.... Ok so if it's not working then there is nothing that can be done?
Is it likely to work if the custom domain is added during deployment?

**Comment by FBoucher** [comment]
@DamienCalvert  It's a bug. 
I would like a clean solution. Right now, not sure why the request.Host return the azure generated name instead of the domain.

UrlList.cs (line 70)
```csharp
var host = req.Host.Host;
foreach (ShortUrlEntity url in result.UrlList)
{
         url.ShortUrl = Utility.GetShortUrl(host, url.RowKey);
}
```

There is many fixes possible... looking for the clean or best one. Should be fix soon.
