### ISSUE TITLE
Blazor Admin - Long URL cut of h in https

### ISSUE THREAD

**Issue by fs366e2spm** [FBoucher/AzUrlShortener#97]
Hi,

Thanks for implementing the #74 for long urls to end them with "...". Unfortunately I guess there's still an error in displaying long urls. For long urls the first h in https:// is cut off.
![Unbenannt](https://user-images.githubusercontent.com/52791126/83354316-261b6300-a358-11ea-847d-01f92010da45.png)

If I'm right the GetDisplayableUrl() in:
src/adminTools/adminBlazorWebsite/src/Data/ShortUrlEntity.cs
starts with character 1 instead of 0, so it cut off the first character, right?

`public string GetDisplayableUrl(){
            var lenght = Url.ToString().Length;
            if (lenght >= 50){
                return string.Concat(Url.Substring(1,50), "...");
            }
            return Url;
        }`

**Comment by FBoucher** [comment]
OMG! LOL
yep it's a bug... A very easy to fix... Any takers?

**Comment by FBoucher** [comment]
in dev

**Comment by FBoucher** [comment]
merged with #127
